### ISSUE TITLE
JWK.get_curve('P-256') fails with KeyError

### ISSUE THREAD

**Issue by ldanielburr** [simo5/jwcrypto#12]
Example:
```python
>>>> from jwcrypto import jwk
>>>> k = jwk.JWK(generate='EC', curve='P-256')
>>>> k.get_curve('P-256')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ldb/virtualenvs/Amsonia/site-packages/jwcrypto/jwk.py", line 358, in get_curve
    if arg and k['crv'] != arg:
KeyError: 'crv'
>>>> 
```
So, it appears that 'crv': 'P-256' is not added to the JWK's _key dict when the object is created.

**Comment by simo5** [comment]
It seem like for some reason I called the param 'curve' in the generation function.
This is clearly a bug, thanks for reporting, I'll attack it soon.

**Comment by simo5** [comment]
Just to be clear, I named it curve instead of 'crv' which is the official RFC name.

In the short term you can work it around by calling:
k = jwk.JWK(generate='EC', curve='P-256', crv='P-256')

I will later make sure both parameters can be used for backwards compatibility and slowly deprecate 'curve'

**Comment by ldanielburr** [comment]
Thanks very much for looking into the issue.
